# -*- coding: utf-8 -*-
"""Another copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7pGBqp6oyVS4BU6lYbQY4f40_IWYROh

# `Colab para manejo de proyecto curso MLDS`
"""

!cat /etc/os-release

"""Podemos instalar git con el siguiente comando:"""

!apt install git

"""Pra ver mejor los comandos de consola"""

!apt install tree

"""Validamos que la herramienta se encuentra instalada:"""

!git --version

"""Importamos las librerías necesarias:"""

import os
from IPython import get_ipython

!pip install dvc dvc-gdrive

"""Crear carpeta para almacenar el proyecto"""

!mkdir 'proyecto'

"""Entramos a la carpeta del proyecto"""

# Commented out IPython magic to ensure Python compatibility.
# %cd 'tdsp_E16'

"""Validar ubicacion"""

!pwd

"""Inicializamos git"""

!git init

"""Ver el contenido de un archivo"""

!cat rand.py

!ls

"""Ejecutar un script ede python"""

!python rand.py

"""Verificar el estado de git"""

!git status

"""Identificarnos como usuarios en git para realizar los commit"""

!git config --global user.email "2548708+HICWhiteFox@users.noreply.github.com"
!git config --global user.name "Claudia Lorena Cañon Diaz"
!git config --global init.defaultBranch master

"""Agregar y hacer commit"""

!git add rand.py
!git commit -m "Cambiamos el tipo de distribución"

"""token github"""

token = "" # Agregue su token dentro de las comillas.

"""Repositorio github"""

repo_url = "https://github.com/HICWhiteFox/tdsp_E16" # Agruegue la url de su repositorio dentro de las comillas.

"""Ahora, usaremos una expresión regular para reemplazar el token en esta url:"""

import re
pat = re.compile(r"(https://)(.*)")

"""Formatear URL"""

match = re.match(pat, repo_url)
url_token = "".join([match.group(1), token, "@", match.group(2)])
os.environ["GITHUB"] = url_token

"""Clonar repositorio"""

!git clone $GITHUB

!git remote add origin $GITHUB

"""Acceder a los datos del proyecto"""

import os

os.environ['KAGGLE_USERNAME'] = "claudiacanon"

os.environ['KAGGLE_KEY'] = ""

!kaggle datasets download -d arseniitretiakov/noticias-falsas-en-espaol/
!unzip noticias-falsas-en-espaol.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd '../..'

!head fakes1000.csv

"""inicializamos dvc"""

!dvc init

"""REgistrar datos para el seguimiento"""

!dvc add scripts/data_acquisition/fakes1000.csv scripts/data_acquisition/onlyfakes1000.csv scripts/data_acquisition/onlytrue1000.csv

!ls -a scripts/data_acquisition/

!cat scripts/data_acquisition/.gitignore

!cat scripts/data_acquisition/fakes1000.csv.dvc

!git add scripts/data_acquisition/.gitignore scripts/data_acquisition/*.csv.dvc

!git status

!git commit -m "Inicializamos dvc y agregamos los datasets de noticias falsas y verdaderas"

!git push origin master

drive_id = "1UjvpSrrzjaYcWawe4yNR4rleCxa8mviZ" # reemplace aquí el id de su carpeta
os.environ["DRIVEID"] = drive_id

!dvc remote add -d storage "gdrive://$DRIVEID"

!dvc remote modify storage gdrive_use_service_account true

import json
with open("../credentials.json") as f:
    os.environ["GDRIVE_CREDENTIALS_DATA"] = f.read()

!git add .dvc/config
!git commit -m "Agregamos drive remoto a dvc para el proyecto de noticias falsas"

!dvc push

!pwd
